name: random_name_generator
description: An app to generate full name by call api from an api developed by https://randomuser.me/ 

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  firebase_analytics: ^8.3.4
  firebase_core: ^1.10.0
  firebase_crashlytics: ^2.3.0
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icons.png"

flutter:
  uses-material-design: true
